FROM {{ source_image }}
LABEL modified_append_tag={{ modified_append_tag }}

WORKDIR /
USER root

COPY yum_install.sh /tmp/

{% if yum_repos_dir_path is defined %}
RUN rm -rf /etc/yum.repos.d/
COPY yum.repos.d /etc/yum.repos.d
COPY repos /
{% endif %}

RUN /tmp/yum_install.sh "{{ yum_packages | join(' ') }}"

USER "{{ original_user }}"
